baseURL: "https://vanleeuw.io/"
title: vanleeuw.io
languageCode: en-us
theme: PaperMod
enableRobotsTXT: true

minify:
  disableXML: true
  minifyOutput: true

params:
  description: "company website for vanleeuw.io"
  author: [ "Anton Vanleeuw" ]