version: '3.8'

services:
  website:
    image: vanleeuw.io/website
    build:
      context: .
      dockerfile: ./Dockerfile
    command: hugo server -D --bind 0.0.0.0
    ports:
      - "1313:1313"
    volumes:
      - .:/src